### ISSUE TITLE
Do not show key when typing it in unlock account form by default.

### ISSUE THREAD

**Issue by antanst** [Regulus343/Nxs#1]
The "show phrase" field should be unticked by default.

**Comment by Regulus343** [comment]
This one is also adjustable in the config file under "secretPhraseFieldDefaultVisible". Perhaps I will make it hidden by default.

**Comment by Regulus343** [comment]
I am going to leave this on by default as it can be easily turned off in the config file, and new users will benefit from being able to see their secret phrases so they can copy and paste a phrase created with the "Generate" button into a text editor for safe-keeping.
