### ISSUE TITLE
"Your secret phrase is too short." dialog should not prevent user from using specified phrase.

### ISSUE THREAD

**Issue by antanst** [Regulus343/Nxs#2]
The warning is nice, however it should allow one to proceed with the short phrase instead of not letting him use it. I usually log in with small "test" phrases for debugging purposes.

**Comment by Regulus343** [comment]
You can turn this requirement off actually by opening "assets/js/config.js" and turning the "secretPhraseRequireStrong" variable to "false". You will still get a warning about having an insecure secret phrase, but you will still be allowed to use it after clicking "OK" on the warning window. I always turn this off for my own testing purposes. It is on by default to prevent new users that might not be aware of the need for much stronger password than they're used to.
