### ISSUE TITLE
Account hash differently compared to nrs

### ISSUE THREAD

**Issue by kalongerber** [Regulus343/Nxs#6]
In trying to log into an existing account which was created with nrs, I noticed that the same pass phrase hashed to a different account number.

**Comment by Regulus343** [comment]
I saw this reported once on the Nxtcrypto forum, but the person never gave me any information with which to troubleshoot the issue. Does your phrase make use of any special characters?

The unlocking function is basically a reworked version of the NRS unlocking function, so I'm not sure why the result would be different (all my phrases get the same account number with both). Anyway, I'll do some more testing over the next few days to try to get to the bottom of this issue. Thanks for the report.

**Comment by Regulus343** [comment]
I have reproduced and corrected the issue. Javascript's encodeURIComponent() was being used on the secret phrase, which was being encoded again by jQuery's ajax() method.
